# Cargo.toml

[package]
name = "my-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
# Web framework
actix-web = { version = "4", features = ["rustls-0_23"] }
# Serialization and deserialization
serde = { version = "1", features = ["derive"] }
serde_json = "1"
# Unique identifiers
uuid = { version = "1", features = ["v4"] }
# Async runtime logging
env_logger = "0.11"
log = "0.4"
# Date and time handling
chrono = { version = "0.4", features = ["serde"] }
# Environment variable loading
dotenvy = "0.15"
actix-cors = "0.7.1"
sqlx = { version = "0.8.6", features = ["runtime-tokio", "postgres", "chrono" ]  }
dotenv = "0.15" # To manage environment variables
rustls = "0.23.38"
rustls-pemfile = "2"
argon2 = "0.5.3"
jsonwebtoken = { version = "10.3.0", features = ["aws_lc_rs"] }
# actix-jwt-auth-middleware = "0.5.0"
# ed25519-compact = "2.2.0"
# jwt-compact = { version = "0.8", features = ["ed25519-compact"] }
actix-web-httpauth = "0.8"
itertools = "0.14"
